[package]
name = "api"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.0", features = ["rt-multi-thread", "macros"] }
prost = "0.14"
prost-types = "0.14.1"
tonic = { version = "0.14.2" }
tonic-prost = "*"

[build-dependencies]
tonic-prost-build = "*"
